// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkyjkjrgmpvtykvtitbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1reWpranJnbXB2dHlrdnRpdGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDg3OTAsImV4cCI6MjA2ODU4NDc5MH0.xNAeHuj4E6AIXHhiPFg59x5HfWBoqJcpVlezLbNj1D0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});